### ISSUE TITLE
Revisione Joint o Muscoli

### ISSUE THREAD

**Issue by fbarchi** [Meldor/Karl-Sims-Resurrection#1]
Vediamo se riusciamo ad usare i Revolute Joint che sembrano la cosa più simile al progetto originale

**Comment by Meldor** [comment]
Fatto. Con "a" abiliti i muscoli, con "m" i motori dei Revolute Joint. Ho fatto in modo che l'intensità della forza applicata e la coppia massima dipendono dalla dimensione della parte, la velocità del motore dal raggio del giunto.
Diciamo che la differenza nel comportamento utilizzando un sistema piuttosto che l'altro è che utilizzando il motore, in assenza di ostacoli, questo si muove a velocità costante (a meno di raggiungere la coppia massima) e, se non si invia un comando, il motore tende a rimanere bloccato (applica una coppia per opporsi a eventuali forze che farebbero ruotare le due parti). Utilizzando i muscoli invece la forza è costante quindi il moto è accelerato (in assenza di ostacoli) e non applicando nessuna forza il giunto resta libero (non tende a mantenere ferme le due parti). A te quale sembra la modalità migliore?

**Comment by fbarchi** [comment]
Da come hai descritto le due modalità pare più realistico l'uso dei muscoli... solo che non riesco vedere le differenze in fase di simulazione, una volta creato il giunto se passo da motore a muscoli la risposta della creatura è quella descritta dall'uso del motore, nel senso che le due parti tendono a rimanere nella stessa posizione..

**Comment by Meldor** [comment]
Infatti mi ero dimenticato di disabilitare il motore quando si passava ai muscoli, ora mi sembra che il comportamento sia quello previsto.

**Comment by fbarchi** [comment]
Ok adesso funziona :) tu quale dei due metodi pensi sia il migliore?

**Comment by Meldor** [comment]
Sì anche a me sembra più realistico usare i muscoli; i motori mi sembra siano più adatti se volessimo costruire dei bracci robotici, che devono muoversi in ben precise posizioni e mantenerle. Ad ogni modo per come ho riscritto la classe FParte è un attimo passare da una modalità all'altra (ad esempio se ci rendessimo conto che con creature più complesse i muscoli danno problemi), basta variare PartMotionSystem.

**Comment by fbarchi** [comment]
Perfetto allora teniamo tutto così e usiamo di default gli attuatori...
