### ISSUE TITLE
Rilevamento collisioni

### ISSUE THREAD

**Issue by Meldor** [Meldor/Karl-Sims-Resurrection#4]
Far sì che una parte possa rilevare un contatto (con un'altra parte o con il pavimento), per poter poi costruire dei sensori di contatto che saranno degli input del cervello.

**Comment by Meldor** [comment]
Finalmente sono riuscito ad inserire il rilevamento delle collisioni :) ho trovato una funzione, GetWorldManifold, che estrae i punti di contatto dai Manifold dei vari Contact, da cui ho derivato i lati interessati da una collisione. Le informazioni sulle collisioni sono memorizzate nel vettore bool CollidingSides, che è un vettore di flag che indica, per ogni lato, se questo è interessato o meno da almeno una collisione; a livello di visualizzazione i lati che non sono interessati da collisioni sono disegnati verdi mentre quelli interessati da almeno una collisione rossi, mentre i punti di collisione della parte selezionata sono in viola. Se una collisione interessa in maniera inequivocabile un solo lato (ad esempio:
![lato1](http://img15.imageshack.us/img15/7743/collisionelato2.jpg) o ![lato2](http://img810.imageshack.us/img810/5919/collisionelato1.jpg)) non ci sono problemi: solo su quel lato viene riconosciuta la collisione. Se invece la collisione interessa un solo angolo (ad esempio qui:
![angolo](http://img195.imageshack.us/img195/8131/collisioneangolo.jpg))
vengono attivati entrambe i lati che fanno capo a quell'angolo.

**Comment by fbarchi** [comment]
Grande!! I punti di contatto sono precisissimi! :) Ora do un'occhiata al codice

**Comment by Meldor** [comment]
Comunque Git funziona benissimo: tutto il codice relativo alle collisioni l'ho scritto sulla versione del progetto prima che iniziassi il client grafico (quindi senza i file del client grafico e senza il metodo Big Brother in Game1.cs) e ho rinominato Coord.cs in Utils.cs perché mi sembrava più appropriato; mi aspettavo di dover fare un merge manuale dei file con le varie modifiche invece ha fatto tutto in automatico :)

**Comment by fbarchi** [comment]
Bhè poi quando ci vediamo per la prossima "riunione" mi spieghi bene le modifiche perchè dando un'occhiata veloce mi sono perso XD sto lavorando alla rete neurale... a giorni pubblico qualcosa e ne parliamo!
